# Use a Node.js image as base
FROM node:16

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY ./server.js .

# Expose the port your app runs on
EXPOSE $MICROSERVICE_PORT

# Command to run your app
CMD ["npm", "run", "start:server"]